import Head from 'next/head'
import Header from '../components/sections/Header'
import Hero from '../components/sections/Hero'
import About from '../components/sections/About'
import WorkExperience from '../components/sections/WorkExperience'
import Skills from '../components/sections/Skills'
import Projects from '../components/sections/Projects'
import Contact from '../components/sections/Contact'
import skillsContent from '../utils/projectsData'


export default function Home() {
  return (
    <div className='bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden z-0 scrollbar scrollbar-track-gray-400/20 scrollbar-thumb-[#f7af0a]/80'>
      <Head>
        <title>Rishabh-Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Hero />
      <About />
      <WorkExperience />
      <Skills />
      {/* {skillsContent.map((skill) => {
        return <Projects key={skill.img} img={skill.img} heading={skill.heading} desc={skill.desc} />
      })} */}
            <Projects/>

      
      
      
      <Contact />


    </div>
  )
}
