const skillsContent = [
    {
        img:"https://rishabhsharma-portfolio.vercel.app/fonts/html/html5-without-wordmark-color.svg",
        proficiency:"85%"
    },
    {
        img:"https://rishabhsharma-portfolio.vercel.app/fonts/css/css-3-seeklogo.com.svg",
        proficiency:"85%"
    },
    {
        img:"https://rishabhsharma-portfolio.vercel.app/fonts/js/javascript-js-seeklogo.com.svg",
        proficiency:"85%"
    },
    {
        img:"https://rishabhsharma-portfolio.vercel.app/fonts/c++/c-seeklogo.com.svg",
        proficiency:"85%"
    },
    {
        img:"https://rishabhsharma-portfolio.vercel.app/fonts/python/python-seeklogo.com.svg",
        proficiency:"85%"
    },
    {
        img:"https://rishabhsharma-portfolio.vercel.app/fonts/react/react-seeklogo.com.svg",
        proficiency:"85%"
    },
    {
        img:"https://rishabhsharma-portfolio.vercel.app/fonts/nextjs/next-js-seeklogo.com.svg",
        proficiency:"85%"
    },
    {
        img:"https://rishabhsharma-portfolio.vercel.app/fonts/nodejs/nodejs-seeklogo.com.svg",
        proficiency:"85%"
    },
    {
        img:"https://rishabhsharma-portfolio.vercel.app/fonts/ts/typescript-seeklogo.com.svg",
        proficiency:"85%"
    },
    {
        img:"https://rishabhsharma-portfolio.vercel.app/fonts/tailwind/tailwind-css-seeklogo.com.svg",
        proficiency:""
    },
    {
        img:"https://rishabhsharma-portfolio.vercel.app/fonts/firebse/firebase-seeklogo.com.svg",
        proficiency:"85%"
    },
    {
        img:"https://rishabhsharma-portfolio.vercel.app/fonts/git/git-seeklogo.com.svg",
        proficiency:"85%"
    },
    {
        img:"https://rishabhsharma-portfolio.vercel.app/fonts/linux1/tux-seeklogo.com.svg",
        proficiency:"85%"
    },
    {
        img:"https://rishabhsharma-portfolio.vercel.app/fonts/mongodb/mongodb-seeklogo.com.svg",
        proficiency:"85%"
    },
    {
        img:"https://rishabhsharma-portfolio.vercel.app/fonts/sql/mysql-seeklogo.com.svg",
        proficiency:"85%"
    },
    {
        img:"https://s.w.org/style/images/about/WordPress-logotype-wmark-white.png",
        proficiency:"85%"
    }
]
export default skillsContent;